### ISSUE TITLE
how to securely create roles with passwords in sqitch

### ISSUE THREAD

**Issue by lifeiscontent** [sqitchers/sqitch#394]
given a deploy file as such

``` sql
-- Deploy roles/app_user/role to pg

BEGIN;

CREATE ROLE app_user LOGIN PASSWORD 'xyz';

COMMIT;
```

how would you not commit passwords into source like this?
other grants would potentially require the use of this role, so I'd like to store the role as a dependency.

**Comment by theory** [comment]
I recommend creating group roles, rather than user roles, in Sqitch, with all the permissions required for a particular role, but create the connecting roles that are members of the group roles separately, by a DBA or similar.

I also suggest you post questions such as this to the [mail list](
https://groups.google.com/forum/#!forum/sqitch-users), rather than here. Thank you!

**Comment by river-matt** [comment]
I have the same question. I don't want to hardcode passwords into the deploy scripts when I'm creating roles. Is there a way to reference a .env file or ~/.sqitch or something in the SQL?

**Comment by theory** [comment]
No, Sqitch does not modify change scripts in any way. They are all native to the CLI for which they are written. If you're using `psql`, for example, you can use `\i` to include another file that sets variables. Or you can include the variables in your script and specify their values on the command line using `--set`.
