### ISSUE TITLE
Reverts to HEAD not picking up changes. Have to point directly to previous deploy

### ISSUE THREAD

**Issue by altadoctrina** [sqitchers/sqitch#404]
OS: Windows 10
Sqitch Engine: Snowflake

C:\Users\usr\sqitch_folder\flipr> sqitch revert --to @HEAD^ -y
No changes deployed since: "@HEAD"

**Comment by theory** [comment]
Woah, are you using the Snowflake engine already? I haven't even released it yet!

Try `@HEAD^` — all caps.

**Comment by machscott** [comment]
Working through the Snowflake tutorial today (also on Windows 10) and I am having the same issue.  I am using "@HEAD^" (@Head^ resolved in an unknown change).

**Comment by machscott** [comment]
Meant to say that I am using "@ HEAD" (without the space).  Didn't realize at first that it was resolving to reference someone's account.

**Comment by mwessman** [comment]
I have a similar issue where I try to revert the last change by running:
`sqitch revert --to @HEAD `
And the error I get is: "No changes deployed since: "@HEAD""

Now if i run:
`sqitch revert --to @HEAD^`
Then it wants to revert the second-most deployed change. The only solution is to revert everything or create a new deployment so that I can revert the second-most deployed change.

**Comment by theory** [comment]
I'll have to git up my Windows VM and mess with this.

**Comment by theory** [comment]
I just tried it with SQLite, and it properly reverted the change, but only after I double-quoted it:

```
sqitch revert db:sqlite:try.db --to "@HEAD^"
```

When I tried it without quotation marks, it prompted me with `More?`. I assume the caret means something to `cmd.exe`, because it worked fine without the caret.

Anyway, does it work for you with double quotes?

**Comment by theory** [comment]
Heya @altadoctrina and @machscott: Can you confirm whether or not using double-quotes fixes the issue for you? Thanks!

**Comment by theory** [comment]
Closing, should work with double-quotes on Windows.

**Comment by nags28** [comment]
i am facing same issue in Linux 
![image](https://user-images.githubusercontent.com/46648905/126620617-904bc526-2d06-4352-9903-65570a4ec72e.png)

**Comment by theory** [comment]
Use single quotes on Linux. Or no quotes
