### ISSUE TITLE
Is it possible to get metrics on a sqitch deploy/revert/verify for snowflake? 

### ISSUE THREAD

**Issue by caseylargent** [sqitchers/sqitch#431]
Is there a way to get certain metrics from running a sqitch deploy onto Snowflake? Metrics such as Throughouput, top end/limit, those kinds of metrics. Is this something that would need to be done to the ODBC Driver or snowsql specifically?

**Comment by theory** [comment]
No, there is not. I'm not even sure what you mean by these things. IME the performance of Snowflake, which is abysmal for Sqitch, is in the need to authenticate with a token for every request (which means the Sqitch database connection and the execution of the registry script on the first deploy, an each deploy/verify/revert script) and the internals of Snowflake. I presume it's optimized for queries rather than DDL.

**Comment by caseylargent** [comment]
I guess my real question would be to see how long an ODBC connection is open for, which could be a good indication of how long a query takes to connect, run a query, and return the "results"

**Comment by theory** [comment]
Sqitch is a tool for managing database schema changes. It's not a general-purpose query tool. Are you thinking of something else?
