### ISSUE TITLE
Multiple projects without URI

### ISSUE THREAD

**Issue by Conding-Brunna** [sqitchers/sqitch#450]
When registering a second project without an URI the second project can not be added.

Error: 
`Cannot register "second_project" with URI {uri}: project "first_project" already using that URI`

**Comment by theory** [comment]
Project URIs must be unique. Are they not?

Or are you just reporting on the fact that the error message is missing the URI (it should appear where you see `{uri}`)?

**Comment by Conding-Brunna** [comment]
Yes they are unique.

This error occures when you do not set a URI at all (NULL value in sqitch registry database).
It's not possible to have multiple Projects without a URI.

**Comment by Conding-Brunna** [comment]
As far as i can see the problem is this else path of this check seems to be the problem:

https://github.com/sqitchers/sqitch/blob/1e6705bf6ffe379dd314429220f3c9842a5ec9c1/lib/App/Sqitch/Role/DBIEngine.pm#L370-L383

At this point it is already known, that there is no other project with the same name. 
But if there is an existing project without an URI `$res` will contain that project. 
Therefore an error will be thrown.

**Comment by theory** [comment]
Yes, you're quite right. Thank you for the analysis! I'll make sure this gets fixed before v1.0.0 drops.

**Comment by theory** [comment]
Hrm. I'm a bit at a loss now. I had thought that project names had to be unique unless there was a URI, in which case the URI had to be unique. But that's not how I wrote the code, and I'm not sure why. Instead, project names must *always* be unique: it's the primary key!

https://github.com/sqitchers/sqitch/blob/ce8c93e23b0afa4afc144dc862a68365ca76d49e/lib/App/Sqitch/Engine/pg.sql#L21-27

Furthermore, the code explicitly allows only one row to have a `NULL` URI, as shown in the snippet you site. That check was added way back in 4b695d6, in August 2012, when the Postgres engine was the *only* engine. The `projects` table was added just a week earlier, in 0e7a3283e, so it has always had a primary key constraint on the project name, and that has been consistently applied across all the other engines.

I'm tempted to revise the documentation, for now, to state:

> Project names and URIs are both required and must be unique.

Although that's pretty lame. What it was intended to be was:

> Project names must be unique, unless there is also a URI, in which case the URI must be unique.

But fixing it to actually hew to that description would be a PITA, requiring a patch for every engine that must be applied to every existing installation. Since no one ever noticed this inconsistency before, I'm somewhat loathe to do that. Thoughts?

**Comment by theory** [comment]
Oh, and the reason `projects.project` is a primary key is so that other tables can refer to it, e.g.,

https://github.com/sqitchers/sqitch/blob/ce8c93e23b0afa4afc144dc862a68365ca76d49e/lib/App/Sqitch/Engine/pg.sql#L36-L41

Which would not be useful to change.

**Comment by theory** [comment]
Digging a little deeper, it seems that my memory may be flawed: I can't find anywhere saying that the name doesn't have to be unique, other than the code that checks for the existence of the name in the database already. In fact, the `init` docs say:

> Optional URI to associate with the project. If present, the URI will be
> written to the project plan and used for added uniqueness in hashed object
> IDs.

And the tutorial says:

> Now that we have a repository, let's get started with Sqitch. Every Sqitch
> project must have a name associated with it, and, optionally, a unique URI. We
> recommend including the URI, as it increases the uniqueness of object
> identifiers internally, so let's specify one when we initialize Sqitch:

So it's all about increasing the uniqueness of object identifiers, no the identity of projects. So I think it's probably best to leave all the constraints as-is, and perhaps remove some of the code that's never reached thanks to the primary key constraint on `projects.project`.

**Comment by theory** [comment]
Wrote a [detailed list post](https://groups.google.com/d/msg/sqitch-users/7RG3rCxxXQk/qWZDinZtDAAJ) to solicit feedback from others on what to do here.

**Comment by Conding-Brunna** [comment]
In my opinion your first option (just remove the URI checks and leave everything else as is) would be the easiest and best way.

Personally I do not need the URI at all but as you said removal would be a lot of work for little gain (just don’t use it and everything is fine).

If you choose to remove it later it could be a good idea to discourage its use in the documentation. 
Other than that I would not put too much work in it as apparently nobody else wants to leave the URI empty.

**Comment by theory** [comment]
Yes, I think option 1 is the only one that makes sense at this point. I don't see removing URI at any point, frankly, and might want to extend it in the future. But for now, it's best to get things out of the way of project names.

**Comment by theory** [comment]
Hey, I finally found where URI is relevant! If you try to deploy a project with the same name and different URI as one already deployed, it will fail. This helps prevent conflicts between projects. I spelled this out more clearly in doc changes in 8c9aef5.
