### ISSUE TITLE
Keep `sqitch` helper schema within separate database

### ISSUE THREAD

**Issue by grzegorzk** [sqitchers/sqitch#466]
Hi, I'm new to `sqitch` so please bare with me as maybe I've just missed something from manuals.

I'm trying to make `sqitch` to store its own data within separate database (not only schema). I'm on postgresql.

Documentation says that I can change `sqitch` default schema **or** registry in which `sqitch` stores its own data by using `--registry` option. (https://sqitch.org/docs/manual/sqitch-deploy/)

I tried different values, i.e. `sqitch.sqitch`, `sqitch/sqitch`, `sqitch:sqitch` - none worked.

I found this old issue #238 but I did not manage to follow the author of this issue so I guess maybe he was on different database engine?

I'd appreciate if you could hint me how to get `sqitch` to store its own data within separate database.

**Comment by theory** [comment]
You cannot store the Sqitch registry inside another Postgres database. This is by design, for the case where the same project gets deployed to multiple databases, each has its own registry. Storage in a separate database is supported only for those engines that don't have proper schema support, such as MySQL and SQLite.

**Comment by grzegorzk** [comment]
Thanks for clarification. In such case is there an option to make `sqitch` to disable triggers within its own schema?

**Comment by theory** [comment]
The [Sqitch registry schema](/sqitchers/sqitch/blob/develop/lib/App/Sqitch/Engine/pg.sql) has no triggers.
