### ISSUE TITLE
Changes Table Missing for Snowflake

### ISSUE THREAD

**Issue by jamiefdhurst** [sqitchers/sqitch#483]
When trying to run a first deployment for sqitch following the tutorial here: https://github.com/sqitchers/sqitch-snowflake-intro I run into the following problem:

```
sqitch deploy db:snowflake://username@password@account.region/dw_ci?Driver=Snowflake;warehouse=ci_wh
Adding registry tables to db:snowflake://ci:@account.region.snowflakecomputing.com/dw_ci?Driver=Snowflake;warehouse=ci_wh
250001 (08001): Failed to connect to DB. Verify the account name is correct: sol
"snowsql" unexpectedly returned exit value 1
```

Checking the registry tables available, it appears to be trying to act on a table `changes` that does not exist within the registry - therefore even creating the tables manually isn't having an effect (looking at https://github.com/sqitchers/sqitch/blob/develop/lib/App/Sqitch/Engine/Upgrade/snowflake-1.0.sql)

Is the original definition of the `changes` table missing from the Snowflake registry definition?

**Comment by theory** [comment]
That looks like an authentication failure:

```
250001 (08001): Failed to connect to DB. Verify the account name is correct: sol
"snowsql" unexpectedly returned exit value 1
```

**Comment by theory** [comment]
Also, looks like you're using the username `ci` in your URI, but the error reports the account as `sol`. Check your `~/.snowsql/config` file and comment-out lines you don't want SnowSQL to use. This might be due to a bug in SnowSQL where it prioritizes `~/.snowsql/config` values over environment variables, which I recently reported to Snowflake.

**Comment by jamiefdhurst** [comment]
Thanks for the response. Apologies, trying to obfuscate the connection details has probably created a little confusion...

The account name I'm connecting to actually starts with `sol...` - I can see from logging into Snowflake that the connection was successful and that queries are being successfully performed using the credentials I supplied. The issue seems to be in that the `changes` table is not available within the snowflake registry SQL setup files.

I'm not able to post the ODBC debug logs I saw unfortunately as I'm in a different location, but could send them through later with the full queries it's trying to run. It looks like it has a very similar issue to others in the past (#444, #439) except that the error code now is being reported correctly. I'm definitely using sqitch 1.0.0 so I'm unsure what's causing this...

**Comment by theory** [comment]
It looks like it fails because SnowSQL fails to connect. Sqitch does not use ODBC to create the registry or to run deployment scripts, only to maintain the registry. So when it tries to select form the changes table over ODBC, it fails, notices the table is missing, so goes to deploy the registry schema (which you linked above) via SnowSQL. That fails because of an authentication error. Try commenting out everything in your `~/.snowsql/config` file.

**Comment by jamiefdhurst** [comment]
Thanks for your persistance @theory - modified my `.snowsql/config` file this morning to add creds and I'm now having success :) Many thanks for your response!
