### ISSUE TITLE
sqitch and pgbouncer : relation "changes" does not exist

### ISSUE THREAD

**Issue by cabecada** [sqitchers/sqitch#486]
I have a user reporting the below errors while using sqitch for deployment on postgres.

teams are using sqitch against pgbouncer in "transaction pooling mode" which does not allow prepared statements.

although i may agree on error 1 below, coz it seems sqitch made use of prepared statement, i am not able to convince the user who says, i did not get this error for 2 years on pgbouncer, then why now. (no changes to pgbouncer 1.8 / postgres version 11)

error 2 mostly like looks like it could not find sqitch schema in search path, but resolves on rerun when using port 5432?  hence difficult to reproduce. none of this happens with any other app using pgbouncer with transaction pooling mode.

error 1:
ERROR:  prepared statement "dbdpg_p1_3" does not exist

error 2:
ERROR:  relation "changes" does not exist
LINE 3:               FROM changes

so i would like to know, if there are any known docs wrt usage against pgbouncer ?
or does sqitch set searchpath or use prepared statements at session level ? 

how we install sqitch.
```
RUN apt-get update
RUN apt-get install build-essential cpanminus perl perl-doc -y
RUN apt-get install postgresql libdbd-pg-perl -y
RUN cpanm --quiet --notest App::Sqitch
```

**Comment by theory** [comment]
I have generally recommended that Sqitch deployments not go through PGBouncer, since you don't want to replicate DDLs, but to individual Postgres instances. Maybe it would work if we disabled prepared statements (annoying that PGBouncer doesn't support them yet), but I think it's best to deploy to individual clusters. Maybe they have been doing so for two years without realizing it, somehow?

Not sure about error 2. Do make sure you'er using the latest version of Sqitch, though; the Debian version is pretty old, IIRC.

Might get better feedback from the [mail list](https://groups.google.com/group/sqitch-users), as someone there may also use pgBouncer.

**Comment by cabecada** [comment]
pgbouncer does support prepared statements, we have to make use of session mode instead of transaction mode pooling.
https://pgbouncer.github.io/features.html
also, on DBD::perl layer
https://metacpan.org/pod/DBD::Pg#prepare i guess there is a flag to disable it, just like it is disabled in java apps.

but the issue was why only now when nothing else changed?

is there a way to dump search_path is verbose mode when sqitch runs(i saw in some other issue via some patch), coz tables exist and i am pretty sure this is something to do with search path.
it is ok for us to make use of port 5432 or switch to session mode with pgbouncer, but we need to errors to be reproducible for us to be able to identify where the problem is and make a decision :)
i ran examples on pgbouncer in transaction mode and session mode and also direct postgresql, i could not get the error.
but my schema was a simple create table and drop table, over 100 iterations.



Thanks for replying though. appreciate it.

**Comment by theory** [comment]
Sqitch [enables `pg_server_prepare`](/sqitchers/sqitch/blob/b2c23aae793500308ee1f30c90010f12ec86790f/lib/App/Sqitch/Engine/pg.pm#L118); does disabling it fix the issue?

I agree it's weird that it worked before; I don't notice anything that seems relevant in the [DBD::Pg changes](/bucardo/dbdpg/blob/master/Changes), and Sqitch hasn't changed connection params, either.

You can set [DBI_TRACE](https://metacpan.org/pod/DBI#DBI_TRACE) and it will emit all of the statements, including `SET search_path`, so that might help. Don't see why the number of changes would matter, either, unless it's an error in one of their change scripts, which are run though `psql` with [these options](/sqitchers/sqitch/blob/b2c23aae793500308ee1f30c90010f12ec86790f/lib/App/Sqitch/Engine/pg.pm#L85).

**Comment by theory** [comment]
Hi @cabecada. Were you Abel to get Sqitch working with pgBouncer?

**Comment by cabecada** [comment]
Hey @theory really sorry, could not get back to you. I left work in Nov 2019, so do not know if the developer has seen this issue again. you can close this one for now, unless some one reports something similar. happy new year :)

**Comment by theory** [comment]
Hey, appreciate the reply, @cabecada!
