### ISSUE TITLE
How do I add a change that drops a column without dooming verify to forevermore fail?

### ISSUE THREAD

**Issue by unitof** [sqitchers/sqitch#506]
The first change in my plan—let's say it's called `appschema`—creates my app's overall schema, including creating all its major tables. Let's say one of those tables is `lessons` with columns `chapter`, `section`, and `title`.

Now, a bunch of changes later, I want to drop the `title` column.

I can `sqitch add` a new change with `ALTER TABLE lessons DROP COLUMN name;`. That works fine, but after deploying it `sqitch verify dev` fails, because that first change (`appschema`) fails its `verify` script due to the now-missing `title` column which it checks for. All other changes pass verification, including the one I just deployed (which dropped that column)

I could remember to always run `sqitch verify --from-change tables~`, but these doesn't _feel_ right. Shouldn't an entire plan continue to pass verification? Plus, running it that way is no longer verifying the _rest_ of my scheme defined in `appschema`, the vast majority of which remains untouched.

I considered (and locally tried) `sqitch rework appschema` and edited `deploy/appschema.sql` and `verify/appschema.sql` so that they no longer created or verified the `title` column I'm trying to drop.

However, the `appschema` change is [not idempotent](https://github.com/sqitchers/sqitch/issues/282#issuecomment-176862111)—it contains a ton of `CREATE TABLE`s. So I really shouldn't be reworking it. Plus, the only way to deploy after reworking would be to rebase, reverting all my changes back to an empty database, which obviously would lead to complete data loss in production.

What's the best way to go about this? Is it just expected that, after a change like this which drops a column, the change which created that column will fail to verify? Or is there a better way to add new changes that supersedes an old one, while still allowing each to pass verification?

**Comment by theory** [comment]
Couple of things:

1. Yes, this is the issue with the `verify` command. That's why I  instead always have verify scripts run after each corresponding deploy script, rather than all at once at the end (I write unit tests for the latter, instead). You can configure a project to always run verify scripts on `deploy` with `sqitch config --bool deploy.verify true`.

2. Please subscribe to the [mail list](https://sqitch.org/community/) and post questions there, rather than GitHub, where issues are for bug and feature tracking.
