### ISSUE TITLE
Snowflake | No active warehouse selected in the current session.  Select an active warehouse with the 'use warehouse' command.

### ISSUE THREAD

**Issue by antonyarock** [sqitchers/sqitch#520]
I am getting the below error when deploy using Sqitch deploy command.

sqitch deploy db:snowflake://$USERNAME:$PASSWORD@abc.eu-west-1.snowflakecomputing.com/DEV?Driver=Snowflake;warehouse=DEV_WH

I am following the the deployment guidelines from 
https://medium.com/hashmapinc/ci-cd-on-snowflake-using-sqitch-and-jenkins-245c6dc4c205

The error I am getting is 
No active warehouse selected in the current session.  Select an active warehouse with the 'use warehouse' command.
 (SQL-57P03)

I am using the docker image in my Jenkinsfile as explained in the guide.
image 'hashmapinc/sqitch:snowflake-dev'
      args "-u root -v /var/run/docker.sock:/var/run/docker.sock --entrypoint=''"

Could anyone throw some light on what is causing the error?

**Comment by antonyarock** [comment]
When I pass the role as parameter in the URI I came out of this error. But got into different issue.

250001 (08001): Failed to connect to DB. Verify the account name is correct:

**Comment by theory** [comment]
OOh, I don't recall seeing that Medium post before; nice! However, if you're following that tutorial, it looks like you're using the `hashmapinc/sqitch:jenkins` docker image, which might be where the issue is. But be sure to set all the environment variables *as well as* pass the parameters in the connection URI; there seem to be some places where one is read but not the other, and I haven't had time to track them all down.

**Comment by theory** [comment]
Hi @antonyarock, were you able to get Sqitch working properly with your Snowflake configuration?

**Comment by dlawrences** [comment]
To resolve this, I made sure to set the following environment variable as well: `$SNOWSQL_WAREHOUSE`

**Comment by theory** [comment]
Oh interesting. You should be able to set it in the URI, as well, e.g.,

```
db:snowflake://movera@example/flipr?Driver=Snowflake;warehouse=sqitch
```

It should not hang without it, though.
