### ISSUE TITLE
SnowSQL: Failed to connect to DB. Verify the account name is correct.

### ISSUE THREAD

**Issue by maciejkulinski** [sqitchers/sqitch#523]
I have this setup in `.snowsql/config`:

```ini
[connections]
accountname = ab12345.west-europe.azure
warehousename = MYWAREHOUSE
authenticator = SNOWFLAKE_JWT
username = myusername
rolename = MYROLE
private_key_path = /path/snowflake-rsa-key.p8
```

With `SNOWSQL_PRIVATE_KEY_PASSPHRASE` env var set.

I can connect and access `MYDB` database without an issue using `snowsql`.

However when I'm trying to do a deploy (a very first one) with Sqitch:

```bash
sqitch deploy "db:snowflake://ab12345.west-europe.azure.snowflakecomputing.com/MYDB?Driver=Snowflake;warehouse=MYWAREHOUSE;authenticator=SNOWFLAKE_JWT;uid=myusername;role=MYROLE;priv_key_file=/path/snowflake-rsa-key.p8;priv_key_file_pwd=$SNOWSQL_PRIVATE_KEY_PASSPHRASE"
```

I get to `Adding registry tables to` step, then it hangs for a minute and I get:

```
250001 (08001): Failed to connect to DB. Verify the account name is correct: ab1
"snowsql" unexpectedly returned exit value 1
```

Notice account name in the error message is only part of the actual account. Sqitch is passing wrong account name to SnowSQL?

I'm using SnowSQL 1.2.5 and Snowflake ODBC driver 2.21.3 on MacOS 10.14.6.

**Comment by theory** [comment]
> Sqitch is passing wrong account name to SnowSQL?

Maybe. Try this:

```
accountname = ab12345
region = west-europe.azure
```

Sqitch does not support the region name as part of the account name.

**Comment by maciejkulinski** [comment]
That did the trick! Thank you.

**Comment by theory** [comment]
FWIW, Sqitch *does* support the region as part of the host name.

**Comment by rlsteelman** [comment]
> FWIW, Sqitch _does_ support the region as part of the host name.

Apologies for replying on an old thread.  Homebrew version of Sqitch is 1.0.0.  I'm assuming that the aforementioned fix is in v1.1.1?  I am having the same issue with the region not being supported as a part of the host name.

**Comment by theory** [comment]
I think it has been there from the beginning, since I don't see any mention of it in [Changes](Changes). The problem here was that the OP tried to use the region in the account name.

**Comment by rlsteelman** [comment]
> I think it has been there from the beginning, since I don't see any mention of it in [Changes](Changes). The problem here was that the OP tried to use the region in the account name.

I have the same issue.  If I don't put the region into the default config file, it doesn't pull the region from the URI. It just cuts off after the first 3 characters from the @ symbol. 

If I add the region to the default I still have to include the region in the URI.  At that point I get a connection but then, when it tries to write the schema to the DB it fails and says that it couldn't connect to <name>.<region>.snowflakecomputing.c

Note the .c at the end...not .com.  For whatever reason, it cuts off the o and the m, and then it fails to find the host. It connects on the initial execute, it auths, it starts the warehouse, but then the schema build fails because it tries to hit the URL again but this time something is causing the URL to not be complete.

**Comment by theory** [comment]
Would you mind pasting in an example of the URL (obfuscating or cutting out the password)? Note that on the command-line, you must URL-encode special characters, which, if you're using passwords in the URL, is not uncommon).
