### ISSUE TITLE
Sqitch returns exit code 2 if plan is empty

### ISSUE THREAD

**Issue by ltamrazov** [sqitchers/sqitch#546]
Hi,

This issue is similar to: https://github.com/sqitchers/sqitch/issues/10. 

In our case sqitch returns exit code `2` if the plan is empty:

```
/app # cd ./migrations && sqitch deploy
Nothing to deploy (empty plan)
/app/migrations # echo $?
2
```

I'm wondering if this is intended / accurate. In our case the plan is empty because we don't yet have any migrations to apply - the database is an existing database that has already been initialized.

We have the sqitch plan and deployment in place because it makes it easy to generalize and have it be part of the build - going forward we just need to add migrations.

According to [gnu](https://www.gnu.org/software/bash/manual/html_node/Exit-Status.html#:~:text=All%20of%20the%20Bash%20builtins,invalid%20options%20or%20missing%20arguments.) `2` indicates incorrect usage or missing arguments. In this case, all the arguments are there.

Should the use case of an empty plan be considered incorrect usage?

 Thank you for your time!

**Comment by theory** [comment]
Yes, it's intentional. The thought is that, if you run `sqitch deploy`, it's because you think there is a plan to deploy. And if there is nothing in the plan, that might be unexpected. It's true that there is no inherent error, however. Perhaps the behavior should  be changed.

Sqitch does not follow the bash exit status guidelines (I wasn't even aware of them before now). Looks like they apply only to bash builtins.

**Comment by ltamrazov** [comment]
I'm not sure if this is a widespread issue but your rational makes sense, seems like you can look at it both ways: there is nothing wrong so no need for error OR active protection against empty plans. We have a workaround for our use case where we check the `deploy` directory before running sqitch to see if there is anything there, so this is no biggie. Thank you for the reply!
