### ISSUE TITLE
Changing order of entries in sqitch.plan and eliminating the "Cannot find change..." message

### ISSUE THREAD

**Issue by abhisheikdeo** [sqitchers/sqitch#558]
There was an issue in scripts and I had to change the order of the entries in the script and now I see the `Cannot find change...` error.

How do I specify `sqitch` that this is a deliberate thing and to eliminate this error?

**Comment by theory** [comment]
You need to revert the changes then redeploy them (or use [rebase](https://sqitch.org/docs/manual/sqitch-rebase/)). If you have released the database already, such that reverting is not an option, don't reorder them.

In the future, please post questions to the [mail list](https://sqitch.org/community/) rather than a GitHub issue, which is for issue-tracking rather than Q&A.
